[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/assets/*"
  to = "/static/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/wa/*"
  to = "https://16-16-124-14.nip.io/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
