[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/wa/*"
  to = "https://school-system-backend.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
