services:
  - type: web
    name: school-system-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 10000
